### ISSUE TITLE
Make RSS Dashlet accessible to Portal Users

### ISSUE THREAD

**Issue by ecosysmaat** [Kharg/rss-dashlet#1]
Hi Kharg,

Thanks for this development, nice one.

The thing is that the configuration doesn't seem to let portal users access the display of RSS feeds, see Admin / Portals / [our portal] / User Interface.

Is it possible to make the RSS Dashlet widget accessible to Portal Users by some custom configuration to the code or via the EspoCRM Administration?

Thanks,
Astehmari

**Comment by Kharg** [comment]
Hello,

Thank you for reporting this.


I will fix this issue between today and tomorrow.

**Comment by Kharg** [comment]
Latest version should allow the dashlet to be added to portals.

**Comment by ecosysmaat** [comment]
![Screenshot_2024-04-18_22-19-55_v2](https://github.com/Kharg/rss-dashlet/assets/44122622/cb869164-6d3e-4cd0-8123-46a88f3762ad)

Hi,

Thanks for updating the package, sounds promising.  I installed it but didn't see how i can add the dashlet to the portal user space. 

When i go to  Admin / Portals / [our portal] / User Interface and click to edit the "Tab List" and then "Add" i can't see how to add the Dashlet to the portal.

Please help me to see how the "Latest version should allow the dashlet to be added to portals."

**Comment by Kharg** [comment]
@piu-logistics 

![image](https://github.com/Kharg/rss-dashlet/assets/32223252/6c3a45ad-0829-4f89-a90e-87f7fc51f977)

![image](https://github.com/Kharg/rss-dashlet/assets/32223252/d2a533c2-0a32-4da0-8232-ae26396038ee)

**Comment by ecosysmaat** [comment]
Great, works perfectly.  Thanks for the Pro dev flow.
